---
  ### Send files to ZTP servers
  - name: Send ZTP configurations & softwares to server
    hosts: ztp-servers
    connection: ssh
    gather_facts: no
    vars:
        sync: true
    roles:
      - {role: ztp-push-dhcp, become: yes}
