---
  ztp:
    setup:
      dhcp:
        range: 10.1.1.0
        netmask: 255.255.255.0
        gw: 10.1.1.0
        pool_low: 10.1.1.100
        pool_high: 10.1.1.120
        gateway: 10.1.1.254
        domain_name: lab.jnpr.net
    ftp:
      home_dir: "/var/ftp/"

    configuration:
      method: ftp
      server:
        tftp: 10.1.1.1
        log: 10.1.1.1
        ntp: 10.1.1.1
    path:
      build: "config/ztp"
      ftp_conf: "/conf"
      ftp_root: "/var/ftp"
      soft: "/soft"
      junos_local: config/
