---
- name: Push junos configuration to the FTP server with sync
  synchronize: src={{ztp.path.junos_local}}/ dest={{ztp.path.ftp_root}}/{{ztp.path.ftp_conf}}/ checksum=yes rsync_path="sudo rsync"
  when:
    - sync == true

- name: Push junos configuration to the FTP server
  copy: src={{ item }} dest={{ztp.path.ftp_root}}/{{ztp.path.ftp_conf}}/{{ item | basename  }}
  with_fileglob:
        - "{{build_dir}}/{{ztp.path.junos_local}}/*.conf"
  when:
    - sync == false

- name: Push junos softwares to the FTP server with sync
  synchronize: src={{ztp.path.junos_local}}/ dest={{ztp.path.ftp_root}}/{{ztp.path.ftp_conf}}/ checksum=yes rsync_path="sudo rsync"
  when:
    - sync == true

- name: Push junos softwares to the FTP server {{ build_dir }}/{{ztp.path.software_local}}
  copy: src={{ item }} dest={{ztp.path.ftp_root}}/{{ztp.path.soft}}/{{ item | basename  }}
  with_fileglob:
        - "{{build_dir}}/{{ztp.path.software_local}}/*"
  when:
    - sync == false

- name: Copy dhcp content to dhcp-server
  template: src={{ build_dir }}/dhcpd.conf dest=/etc/dhcp/dhcpd.conf backup=yes
  register: dhcp_config

- name: Restart dhcp service to apply changes
  service: name=isc-dhcp-server state=restarted
  when: dhcp_config.changed
